#!/bin/bash

if [ $# -eq 0 ]
  then
    read -p 'game: ' game
  else
    game=$1
fi

if [ $# -lt 2 ]
  then
    read -p 'port: ' port
  else
    port=$2
fi

cd "${0%/*}"
pwd
node server.js $game $port

read -p '<enter> to exit: '
